### ISSUE TITLE
Change a row or column colors

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/color-box#1]
implement a way to change an entire row or column random colors

**Comment by gamer-1478** [comment]
Hello sir, i had a few questions about this issue, so firstly how would you like to change the entire row to random colors? like should a button be added or such? or should clicking the top color change all the colors in the row? also could be possible for you to explain what the app does and perhaps add it in readme.md? as that may be very helpful. but overall i would like to work on this issue.

**Comment by redxzeta** [comment]
Each box has data 
```
interface IColorBox {
  id: number;
  top: number;
  left: number;
  right: number;
  bottom: number;
  color: string;
}
```

I guess either do a while loop or something until the it reaches the end which would hold -1

maybe a button at the ends of the row or columns which would trigger color changes

**Comment by redxzeta** [comment]
I think u maybe have to fix the styling so probably add like a container

**Comment by gamer-1478** [comment]
Good Evening sir, when i sat down to add the features i soon realized that with the current code it will not be possible to implement them without completely refactoring the project structure, and most of the code, and that is not feasible for me just yet as i am still learning and understanding.  so seeing this i have unassigned myself from this project. Loved the app, and hopefully someone else can contribute.

**Comment by redxzeta** [comment]
@gamer-1478 its okay I can help out if u want

**Comment by mankinchi** [comment]
I can work on this

**Comment by mankinchi** [comment]
But I think this should be fixed first https://github.com/redxzeta/color-box/issues/4. I can work on that one too if you want

**Comment by redxzeta** [comment]
@mankinchi did you still want to work on this?

**Comment by mankinchi** [comment]
Sure. Assign me this

Kind regards,
*
*
*Tri Nguyen*

IT Consultant | Unified Commerce

Level 9, 800 Collins Street, Docklands, VIC 3008

M: 0449 258 526 ( tel:0449%20258%20526 ) | ***@***.***

**Comment by mankinchi** [comment]
@redxzeta so how do you want to do this? Does this include clicking on a box should change everything on its column and row?

**Comment by redxzeta** [comment]
@mankinchi yea I was thinking maybe double click or  right click wou8ld change the column and row
