### ISSUE TITLE
Put the id in the center of the box

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/color-box#2]

**Comment by geeythree** [comment]
I'd like to work on this

**Comment by geeythree** [comment]
Hey, thanks for assigning! 😄 Can you please elaborate more on the issue? After going through the code, I couldn't understand what exactly to do

**Comment by redxzeta** [comment]
at like line 91 you may have to change it display the id ` <ColorBox onClick={() => onClick(x)} bg={x.color} key={x.id} />`
 into 
 ```
 <ColorBox onClick={() => onClick(x)} bg={x.color} key={x.id} >
{x.id}
</ColorBox>
```
and then down below is the styled components where you could add the styling

**Comment by geeythree** [comment]
@redxzeta Awesome! I've made a PR. 😄
